### ISSUE TITLE
Problems with gitbook.io

### ISSUE THREAD

**Issue by altishchenko** [bifravst/firmware#136]
Hi Markus!
Looks like something happened to bifravst.gitbook.io - 404 on every link :(

**Comment by coderbyheart** [comment]
Yes, this is due to bifravst/bifravst#192.

You can always find the latest documentation at https://bifravst.github.io/ (this is also the link on top of https://github.com/bifravst).

**Comment by coderbyheart** [comment]
P.S.: I understand that it can be annoying to have older links now working, but this project is still in a pre-release phase, so I believe it is OK to take some liberties. Once bifravst/bifravst/issues/56 is completed the docs will have a permanent home.

In any case, I will always make sure the https://bifravst.github.io/ always redirects to the latest docs.

**Comment by altishchenko** [comment]
Nah, no problem :)
