### ISSUE TITLE
Button press not transmitted (LTE-m, iBasis)

### ISSUE THREAD

**Issue by coderbyheart** [bifravst/firmware#31]
Despite the device claiming to have sent the message, it never arrives at the broker:

```
[00:26:28.079,315] <dbg> lte_lc.parse_nw_reg_status: Network registration status: 5
[00:26:28.087,585] <inf> cat_tracker: Checking LTE connection...
[00:26:28.094,146] <inf> cat_tracker: LTE link maintained
Encoded message: {
        "btn":  {
                "v":    1,
                "ts":   1584697409409
        }
}
[00:26:28.107,452] <dbg> aws_iot.aws_iot_send: Publishing to topic: 352656100378903/messages
```

Firmware: 1.6.2

**Comment by coderbyheart** [comment]
It works with the same version for NB-IoT

**Comment by simensrostad** [comment]
I am not able to reproduce. I get it to work in both LTE modes.

**Comment by coderbyheart** [comment]
On a DK?

**Comment by simensrostad** [comment]
> On a DK?

Yes

**Comment by simensrostad** [comment]
``{
  "format": "json",
  "payload": {
    "btn": {
      "v": 1,
      "ts": 1584710132940
    }
  },
  "qos": 0,
  "timestamp": 1584710133607,
  "topic": "352656100382111/messages"
}``

**Comment by coderbyheart** [comment]
It works right after boot, it seems to stop working after a while.

**Comment by simensrostad** [comment]
I have experienced a prolonged delay after pushing the button and receiving the message in AWS. But that is never more than 5 seconds. I know from previous testing that this delay can be longer.

**Comment by simensrostad** [comment]
But I am guessing that is not the case if the message is not received at all.

**Comment by coderbyheart** [comment]
I have double checked it now, and I am directly subscribed on the IoT console, the Thingy with NB-IoT (Telia Trio) sends it, the DK with LTE-m (iBasis) does not.

**Comment by coderbyheart** [comment]
Tested again with 3.2.2, iBasis SIM and LTE and it works.
