### ISSUE TITLE
Modem configuration (dynamically send AT commands)

### ISSUE THREAD

**Issue by cmedianu** [bifravst/firmware#40]
my provider requires me to run  "AT+CGDCONT=0,\"IP\",\"the.apn.name\"" to set the APN on startup. It would be nice to have a configuration option to run some AT commands on startup.

**Comment by coderbyheart** [comment]
Agreed, I think it makes sense to have this dynamically configured through the cloud, because these AT commands might even depend on the location of the device (if we have devices roaming in different countries).

**Comment by cmedianu** [comment]
That's even better! But it initially has to be compiled in so it can get to the cloud in the first place, right?

**Comment by coderbyheart** [comment]
Agreed, we need both:

1. ~~a compile time firmware configuration setting that accepts a list of AT commands to be run at startup~~
2. a run time routine that applies a list of AT commands present in the desired device state (after boot and whenever they change)

**Comment by coderbyheart** [comment]
> 1. a compile time firmware configuration setting that accepts a list of AT commands to be run at startup

Doing this compile time is supported by [adding these configs](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/reference/kconfig/CONFIG_LTE_PDP_CMD.html):

```
CONFIG_LTE_PDP_CMD=y
CONFIG_LTE_PDP_CONTEXT="0,\"IP\",\"the.apn.name\""
```

**Comment by coderbyheart** [comment]
I think dynamically modem configuration needs to be handled by the device, based on e.g. network parameters.
