### ISSUE TITLE
Push button: send message to help identify device

### ISSUE THREAD

**Issue by coderbyheart** [bifravst/firmware#5]
When the Button 1 of the device is released it should publish a message with a timestamp to a custom topic.

```json
{
    "btn": {
      "v": 1,
      "ts": 1563968747123
  }
}
```

`v` is the number of the button
`ts` is the timestamp of the release

*Note:* we deliberately do not use the shadow here to

1. demonstrate how to use custom topics and
1. because the button itself is a UI element and not a sensor.

**Comment by simensrostad** [comment]
Lets agree on a custom topic here if that has not been defined yet. @coderbyheart.
how about thingname/distress ? I was thinking something in the direction of a distress/help button that can be used in "emergencies".

**Comment by simensrostad** [comment]
Maybe thingname/notify.

**Comment by coderbyheart** [comment]
I would suggest something more general: `<clientId>/messages`.

**Comment by simensrostad** [comment]
Ok, that works. It seems reasonable given the fact that the button can be used to support a range of different functionalities.

**Comment by coderbyheart** [comment]
Note, the button is not reported on release, but on push, but this is a minor issue.

**Comment by coderbyheart** [comment]
On the 91DK only button 1 works.
