### ISSUE TITLE
Limit how often accelerometer data is stored in circular buffer

### ISSUE THREAD

**Issue by simensrostad** [bifravst/firmware#53]
Frequent motion fills the accelerometer circular buffer in no time. Limit how often this occurs by specifying a configurable amount of time allowed in between storage of buffer entries. The already supported timestamping functionality can be used for this purpose.

**Comment by coderbyheart** [comment]
For the cat tracker purpose I would like to have the highest values stored in the ring buffer (*in case they are not transmitted immediately*), not the most recent ones. Because it is most meaningful to know the movement extremes (also applies to e.g. parcel trackers).
