### ISSUE TITLE
Adding support for 3rd party boards (eg Actinius Icarus nRF9160 Feather)

### ISSUE THREAD

**Issue by alextsam** [bifravst/firmware#55]
Hi there,

This is not really an issue, it's more of a question :) I see that currently you only support Nordic Boards but we would like to add support for the Icarus nRF9160 Feather (www.actinius.com/icarus). Would you accept PRs with modifications to add it?

Thanks!

Alex

**Comment by coderbyheart** [comment]
Yes, I definitely would love to see support for a feather form factor board. I personally have backed the [nRF9160 Feather](https://groupgets.com/campaigns/814-nrf9160-feather) and plan to add support, too!

**Comment by alextsam** [comment]
That's great to hear! I just returned from holidays and I will try to get a PR submitted very soon! Thanks.
